/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BREVO_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CERAMIC_NODE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FRONTEND_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ORBIS_ENVIRONMENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ORBIS_NODE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
